### ISSUE TITLE
query options

### ISSUE THREAD

**Issue by toastyy00** [vanhbakaa/Seed-App-Mine-Seed-BOT-Telegram#12]
please add this script to support query, I know seed query is short lived, but it will be very helpful for multi accounts that are prone to bans due to new accounts for create session.

**Comment by vanhbakaa** [comment]
do u still need it

**Comment by vanhbakaa** [comment]
sorry i forgot

**Comment by toastyy00** [comment]
sure, it will helpful

**Comment by vanhbakaa** [comment]
added

**Comment by toastyy00** [comment]
tysm
