### ISSUE TITLE
Unknown error: unsupported operand type(s) for -=: 'int' and 'NoneType'

### ISSUE THREAD

**Issue by dsmddsmd** [vanhbakaa/Seed-App-Mine-Seed-BOT-Telegram#16]
![Screenshot_562](https://github.com/user-attachments/assets/549c9bfd-f12c-4fbe-93ef-09a43bc27aca)
Unknown error: unsupported operand type(s) for -=: 'int' and 'NoneType'

**Comment by vanhbakaa** [comment]
fixed
