### ISSUE TITLE
Hunting finished but not claim

### ISSUE THREAD

**Issue by ppaaw** [vanhbakaa/Seed-App-Mine-Seed-BOT-Telegram#21]
Its shown Hunt completed, claiming reward...{'code':'invalid-request','message': 'bird is not yours'} 

follow attached picture
![messageImage_1727230701489](https://github.com/user-attachments/assets/1e1e667d-e0d4-4f43-923f-6d303e7397f8)

**Comment by vanhbakaa** [comment]
Use newest version
