### ISSUE TITLE
BadMsgNotification

### ISSUE THREAD

**Issue by iamspa** [vanhbakaa/Seed-App-Mine-Seed-BOT-Telegram#24]
when create session always showing like this
Enter the session name (press Enter to exit): Seed
BadMsgNotification: [17] The msg_id is too high, the client time has to be synchronized.
BadMsgNotification: [17] The msg_id is too high, the client time has to be synchronized.
Welcome to Pyrogram (version 2.0.106)
Pyrogram is free software and comes with ABSOLUTELY NO WARRANTY. Licensed
under the terms of the GNU Lesser General Public License v3.0 (LGPL-3.0).

how to fix this?

**Comment by vanhbakaa** [comment]
check yoor time bro

**Comment by iamspa** [comment]
> check yoor time bro

yes, my time is wrong, even only 1 minute.
thanks for advice
