### ISSUE TITLE
Failed Tools, can you help me?

### ISSUE THREAD

**Issue by alexdo83** [vanhbakaa/Seed-App-Mine-Seed-BOT-Telegram#25]
Failed Tools, can you help me?
![erro](https://github.com/user-attachments/assets/1e9451fb-0a24-4a3d-9982-102fe6df57ec)

**Comment by vanhbakaa** [comment]
Bro please read readme.md or you better leave that field blank

**Comment by SmartWorkBoy** [comment]
same problem even i tried by lefting it blank , I first tried with true then with false not working in situations

**Comment by vanhbakaa** [comment]
> same problem even i tried by lefting it blank , I first tried with true then with false not working in situations

leave all blank except api id and api hash
