### ISSUE TITLE
installing problem

### ISSUE THREAD

**Issue by Mr-Mk7** [vanhbakaa/Seed-App-Mine-Seed-BOT-Telegram#27]
Creating virtual environment...
Activating virtual environment...
installing wheel for faster installing
Collecting wheel
  Using cached wheel-0.44.0-py3-none-any.whl.metadata (2.3 kB)
Using cached wheel-0.44.0-py3-none-any.whl (67 kB)
Installing collected packages: wheel
Successfully installed wheel-0.44.0
Installing dependencies...
Collecting aiocfscrape==1.0.0 (from -r requirements.txt (line 1))
  Using cached aiocfscrape-1.0.0-py3-none-any.whl
Collecting aiohttp==3.9.3 (from -r requirements.txt (line 2))
  Using cached aiohttp-3.9.3-cp312-cp312-win_amd64.whl.metadata (7.6 kB)
Collecting aiohttp-proxy==0.1.2 (from -r requirements.txt (line 3))
  Using cached aiohttp_proxy-0.1.2-py3-none-any.whl.metadata (2.7 kB)
Collecting aiosignal==1.3.1 (from -r requirements.txt (line 4))
  Using cached aiosignal-1.3.1-py3-none-any.whl.metadata (4.0 kB)
Collecting annotated-types==0.6.0 (from -r requirements.txt (line 5))
  Using cached annotated_types-0.6.0-py3-none-any.whl.metadata (12 kB)
Collecting async-timeout==4.0.3 (from -r requirements.txt (line 6))
  Using cached async_timeout-4.0.3-py3-none-any.whl.metadata (4.2 kB)
Collecting attrs==23.2.0 (from -r requirements.txt (line 7))
  Using cached attrs-23.2.0-py3-none-any.whl.metadata (9.5 kB)
Collecting beautifulsoup4==4.12.3 (from -r requirements.txt (line 8))
  Using cached beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
Collecting better-proxy==1.1.5 (from -r requirements.txt (line 9))
  Using cached better_proxy-1.1.5-py3-none-any.whl.metadata (2.6 kB)
Collecting colorama==0.4.6 (from -r requirements.txt (line 10))
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting DateTime==5.5 (from -r requirements.txt (line 11))
  Using cached DateTime-5.5-py3-none-any.whl.metadata (33 kB)
Collecting frozenlist==1.4.1 (from -r requirements.txt (line 12))
  Using cached frozenlist-1.4.1-cp312-cp312-win_amd64.whl.metadata (12 kB)
Collecting idna==3.6 (from -r requirements.txt (line 13))
  Using cached idna-3.6-py3-none-any.whl.metadata (9.9 kB)
Collecting Js2Py==0.74 (from -r requirements.txt (line 14))
  Using cached Js2Py-0.74-py3-none-any.whl.metadata (868 bytes)
Collecting loguru==0.7.2 (from -r requirements.txt (line 15))
  Using cached loguru-0.7.2-py3-none-any.whl.metadata (23 kB)
Collecting multidict==6.0.5 (from -r requirements.txt (line 16))
  Using cached multidict-6.0.5-cp312-cp312-win_amd64.whl.metadata (4.3 kB)
Collecting pyaes==1.6.1 (from -r requirements.txt (line 17))
  Using cached pyaes-1.6.1-py3-none-any.whl
Collecting pydantic==2.6.4 (from -r requirements.txt (line 18))
  Using cached pydantic-2.6.4-py3-none-any.whl.metadata (85 kB)
Collecting pydantic-settings==2.2.1 (from -r requirements.txt (line 19))
  Using cached pydantic_settings-2.2.1-py3-none-any.whl.metadata (3.1 kB)
Collecting pydantic_core==2.16.3 (from -r requirements.txt (line 20))
  Using cached pydantic_core-2.16.3-cp312-none-win_amd64.whl.metadata (6.6 kB)
Collecting pyjsparser==2.7.1 (from -r requirements.txt (line 21))
  Using cached pyjsparser-2.7.1-py3-none-any.whl
Collecting Pyrogram==2.0.106 (from -r requirements.txt (line 22))
  Using cached Pyrogram-2.0.106-py3-none-any.whl.metadata (4.4 kB)
Collecting PySocks==1.7.1 (from -r requirements.txt (line 23))
  Using cached PySocks-1.7.1-py3-none-any.whl.metadata (13 kB)
Collecting python-dotenv==1.0.1 (from -r requirements.txt (line 24))
  Using cached python_dotenv-1.0.1-py3-none-any.whl.metadata (23 kB)
Collecting pytz==2024.1 (from -r requirements.txt (line 25))
  Using cached pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting six==1.16.0 (from -r requirements.txt (line 26))
  Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting soupsieve==2.5 (from -r requirements.txt (line 27))
  Using cached soupsieve-2.5-py3-none-any.whl.metadata (4.7 kB)
Collecting TgCrypto==1.2.5 (from -r requirements.txt (line 28))
  Using cached TgCrypto-1.2.5-cp312-cp312-win_amd64.whl
Collecting typing_extensions==4.11.0 (from -r requirements.txt (line 29))
  Using cached typing_extensions-4.11.0-py3-none-any.whl.metadata (3.0 kB)
Collecting tzdata==2024.1 (from -r requirements.txt (line 30))
  Using cached tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting tzlocal==5.2 (from -r requirements.txt (line 31))
  Using cached tzlocal-5.2-py3-none-any.whl.metadata (7.8 kB)
Collecting websockets==12.0 (from -r requirements.txt (line 32))
  Using cached websockets-12.0-cp312-cp312-win_amd64.whl.metadata (6.8 kB)
Collecting win32-setctime==1.1.0 (from -r requirements.txt (line 33))
  Using cached win32_setctime-1.1.0-py3-none-any.whl.metadata (2.3 kB)
Collecting yarl==1.9.4 (from -r requirements.txt (line 34))
  Using cached yarl-1.9.4-cp312-cp312-win_amd64.whl.metadata (32 kB)
Collecting zope.interface==6.4.post2 (from -r requirements.txt (line 35))
  Using cached zope.interface-6.4.post2-cp312-cp312-win_amd64.whl.metadata (44 kB)
Collecting requests==2.32.3 (from -r requirements.txt (line 36))
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting python-dateutil==2.9.0 (from -r requirements.txt (line 37))
  Using cached python_dateutil-2.9.0-py2.py3-none-any.whl.metadata (8.3 kB)
Collecting setuptools (from zope.interface==6.4.post2->-r requirements.txt (line 35))
  Using cached setuptools-75.1.0-py3-none-any.whl.metadata (6.9 kB)
Collecting charset-normalizer<4,>=2 (from requests==2.32.3->-r requirements.txt (line 36))
  Using cached charset_normalizer-3.4.0-cp312-cp312-win_amd64.whl.metadata (34 kB)
Collecting urllib3<3,>=1.21.1 (from requests==2.32.3->-r requirements.txt (line 36))
  Using cached urllib3-2.2.3-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests==2.32.3->-r requirements.txt (line 36))
  Using cached certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
Using cached aiohttp-3.9.3-cp312-cp312-win_amd64.whl (363 kB)
Using cached aiohttp_proxy-0.1.2-py3-none-any.whl (12 kB)
Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Using cached annotated_types-0.6.0-py3-none-any.whl (12 kB)
Using cached async_timeout-4.0.3-py3-none-any.whl (5.7 kB)
Using cached attrs-23.2.0-py3-none-any.whl (60 kB)
Using cached beautifulsoup4-4.12.3-py3-none-any.whl (147 kB)
Using cached better_proxy-1.1.5-py3-none-any.whl (3.2 kB)
Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Using cached DateTime-5.5-py3-none-any.whl (52 kB)
Using cached frozenlist-1.4.1-cp312-cp312-win_amd64.whl (50 kB)
Using cached idna-3.6-py3-none-any.whl (61 kB)
Using cached Js2Py-0.74-py3-none-any.whl (1.0 MB)
Using cached loguru-0.7.2-py3-none-any.whl (62 kB)
Using cached multidict-6.0.5-cp312-cp312-win_amd64.whl (27 kB)
Using cached pydantic-2.6.4-py3-none-any.whl (394 kB)
Using cached pydantic_settings-2.2.1-py3-none-any.whl (13 kB)
Using cached pydantic_core-2.16.3-cp312-none-win_amd64.whl (1.9 MB)
Using cached Pyrogram-2.0.106-py3-none-any.whl (3.6 MB)
Using cached PySocks-1.7.1-py3-none-any.whl (16 kB)
Using cached python_dotenv-1.0.1-py3-none-any.whl (19 kB)
Using cached pytz-2024.1-py2.py3-none-any.whl (505 kB)
Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Using cached soupsieve-2.5-py3-none-any.whl (36 kB)
Using cached typing_extensions-4.11.0-py3-none-any.whl (34 kB)
Using cached tzdata-2024.1-py2.py3-none-any.whl (345 kB)
Using cached tzlocal-5.2-py3-none-any.whl (17 kB)
Using cached websockets-12.0-cp312-cp312-win_amd64.whl (124 kB)
Using cached win32_setctime-1.1.0-py3-none-any.whl (3.6 kB)
Using cached yarl-1.9.4-cp312-cp312-win_amd64.whl (76 kB)
Using cached zope.interface-6.4.post2-cp312-cp312-win_amd64.whl (206 kB)
Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Using cached python_dateutil-2.9.0-py2.py3-none-any.whl (230 kB)
Using cached certifi-2024.8.30-py3-none-any.whl (167 kB)
Using cached charset_normalizer-3.4.0-cp312-cp312-win_amd64.whl (102 kB)
Using cached urllib3-2.2.3-py3-none-any.whl (126 kB)
Using cached setuptools-75.1.0-py3-none-any.whl (1.2 MB)
Installing collected packages: pytz, pyjsparser, pyaes, win32-setctime, websockets, urllib3, tzdata, typing_extensions, TgCrypto, soupsieve, six, setuptools, python-dotenv, PySocks, multidict, idna, frozenlist, colorama, charset-normalizer, certifi, attrs, async-timeout, annotated-types, zope.interface, yarl, tzlocal, requests, python-dateutil, Pyrogram, pydantic_core, loguru, beautifulsoup4, aiosignal, pydantic, Js2Py, DateTime, aiohttp, pydantic-settings, better-proxy, aiohttp-proxy, aiocfscrape
Successfully installed DateTime-5.5 Js2Py-0.74 PySocks-1.7.1 Pyrogram-2.0.106 TgCrypto-1.2.5 aiocfscrape-1.0.0 aiohttp-3.9.3 aiohttp-proxy-0.1.2 aiosignal-1.3.1 annotated-types-0.6.0 async-timeout-4.0.3 attrs-23.2.0 beautifulsoup4-4.12.3 better-proxy-1.1.5 certifi-2024.8.30 charset-normalizer-3.4.0 colorama-0.4.6 frozenlist-1.4.1 idna-3.6 loguru-0.7.2 multidict-6.0.5 pyaes-1.6.1 pydantic-2.6.4 pydantic-settings-2.2.1 pydantic_core-2.16.3 pyjsparser-2.7.1 python-dateutil-2.9.0 python-dotenv-1.0.1 pytz-2024.1 requests-2.32.3 setuptools-75.1.0 six-1.16.0 soupsieve-2.5 typing_extensions-4.11.0 tzdata-2024.1 tzlocal-5.2 urllib3-2.2.3 websockets-12.0 win32-setctime-1.1.0 yarl-1.9.4 zope.interface-6.4.post2
Copying configuration file
        1 file(s) copied.
Starting the bot...
Traceback (most recent call last):
  File "C:\Users\HOME X\Seed-App-Mine-Seed-BOT-Telegram-main\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\Users\HOME X\Seed-App-Mine-Seed-BOT-Telegram-main\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\Users\HOME X\Seed-App-Mine-Seed-BOT-Telegram-main\bot\utils\launcher.py", line 10, in <module>
    from bot.config import settings
  File "C:\Users\HOME X\Seed-App-Mine-Seed-BOT-Telegram-main\bot\config\__init__.py", line 1, in <module>
    from .config import settings
  File "C:\Users\HOME X\Seed-App-Mine-Seed-BOT-Telegram-main\bot\config\config.py", line 44, in <module>
    settings = Settings()
               ^^^^^^^^^^
  File "C:\Users\HOME X\Seed-App-Mine-Seed-BOT-Telegram-main\venv\Lib\site-packages\pydantic_settings\main.py", line 84, in __init__
    super().__init__(
  File "C:\Users\HOME X\Seed-App-Mine-Seed-BOT-Telegram-main\venv\Lib\site-packages\pydantic\main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for Settings
API_ID
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
API_HASH
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
done
PLEASE EDIT .ENV FILE
Press any key to continue . . .

**Comment by vanhbakaa** [comment]
PLEASE EDIT .ENV FILE
