### ISSUE TITLE
bro warm sell issue

### ISSUE THREAD

**Issue by crypto-kotha** [vanhbakaa/Seed-App-Mine-Seed-BOT-Telegram#29]
async def sell_worm(self, worm_id, price, worm_type, http_client: aiohttp.ClientSession):
        if asyncio.iscoroutine(price):  # Check if it's a coroutine
            price = await price
        payload = {
            "price": price,
            "worm_id": worm_id,
            "type": worm_type
        }
        response = await http_client.post(api_sell, json=payload)
        if response.status == 200:
            self.total_on_sale += 1
            logger.success(
                f"{self.session_name} | <green>Sell {worm_type} worm successfully, price: {price / 1000000000}>        else:
            response_data = await response.json()
            print(response_data)
            logger.info(f"{self.session_name} | Failed to sell {worm_type} worm, response code:{response.statu>
            return None

**Comment by vanhbakaa** [comment]
fixed
