### ISSUE TITLE
Auto sell worms

### ISSUE THREAD

**Issue by toastyy00** [vanhbakaa/Seed-App-Mine-Seed-BOT-Telegram#8]
Add auto sell uncommon worms

**Comment by vanhbakaa** [comment]
Okay

**Comment by GZMWAL** [comment]
> Okay

Looking forward for the update. Thank you for the bot, appreciate your effort :)

**Comment by vanhbakaa** [comment]
done

**Comment by vanhbakaa** [comment]
> works like a charms, but it would be better to auto sell some worms instead of selling them all

added

**Comment by toastyy00** [comment]
Instead of setting the max auto sell amount, it's better to set the amount worms you want to keep.

example : i want to keep 3 uncommon, 4 common, 4 rare and and above that is not for sale. 

if i have
uncommon: 5
common: 3
Rare: 6
it will auto sell 2 uncommon and 2 rare

**Comment by vanhbakaa** [comment]
> Instead of setting the max auto sell amount, it's better to set the amount worms you want to keep.
> 
> example : i want to keep 3 uncommon, 4 common, 4 rare and and above that is not for sale.
> 
> if i have uncommon: 5 common: 3 Rare: 6 it will auto sell 2 uncommon and 2 rare

added

**Comment by toastyy00** [comment]
![image](https://github.com/user-attachments/assets/ef5e05d8-423f-4785-b68c-a67aa70f88b6)
i set like this and all my worms got sell
